---
title: "habituals-priors-BDA"
author: "mht"
date: "November 24, 2015"
output: html_document
---

```{r}
library(data.table)
library(coda)
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
HPDhi<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
HPDlo<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
options("scipen"=10)   
filePath <- "~/Documents/research/habituals/models/priors/results/"
```

```{r data.load}
d<-read.csv("~/Documents/research/habituals/data/priors/priors-2.csv")

scaleTime2 <- list(
  week = 7,
  month = 30,
  year = 365,
  "5 years" = 5*365
)

scaleTime.nTimes <- list(
  week = 5*52,
  month = 5*12,
  year = 5,
  "5 years" = 1
)


d.tidy<- d %>% 
  select(workerid, category, item, ends_with("_men"), ends_with("_women")) %>%
  mutate(menFreq = nPersons_men / comparisonNum_men,
         womenFreq = nPersons_women / comparisonNum_women) %>%
  rowwise() %>%
  mutate(menRate = scaleTime2[[as.character(comparisonTime_men)]]/nInstances_men,
         womenRate = scaleTime2[[as.character(comparisonTime_women)]]/nInstances_women) %>%
  mutate(menRate = ifelse(menRate==Inf, 5*365, menRate),
         womenRate = ifelse(womenRate==Inf, 5*365, womenRate)) %>%
  mutate(item = gsub("sell things on eBay", "sells things on eBay", item))



d.nTimes<- d %>% 
  select(workerid, category, item, ends_with("_men"), ends_with("_women")) %>%
  mutate(menFreq = nPersons_men / comparisonNum_men,
         womenFreq = nPersons_women / comparisonNum_women) %>%
  rowwise() %>%
  mutate(Ntimes_m = scaleTime.nTimes[[as.character(comparisonTime_men)]]*
           nInstances_men,
         Ntimes_f = scaleTime.nTimes[[as.character(comparisonTime_women)]]*
           nInstances_women) %>%
  select(-starts_with("effective"), -starts_with("comparisonNum"),
         -starts_with("nPersons"))%>%
  select(category, item, Ntimes_m, Ntimes_f) %>%
  gather(key, val, -category, -item) %>%
  mutate(logval = log(val),
         gender = factor(key, levels=c("Ntimes_m", "Ntimes_f"),
                         labels=c("male", "female")),
        item = gsub("sell things on eBay", "sells things on eBay", item),
        logval = ifelse(logval==-Inf, 0, logval))


```

## Existence question

```{r q1.load}
prefix <- "priors2-existenceQ-betaModel-incrMH"
samples <- 100000
burn <- samples / 2
m<- as.data.frame.matrix(fread(paste(filePath, prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.csv",sep="")))

m.samples <- m[rep(row.names(m), m$Probability*(samples-burn)), 1:5]
```

### Posterior over parameters

```{r q1.params}
m.params<-m.samples %>% filter(Parameter!='predictive')

ggplot(m.params,aes(x=Value, fill=Gender))+
  geom_histogram(position=position_dodge())+
  facet_grid(Item~Parameter, scales='free')+
  theme(strip.text.y = element_text(angle=0))


ggsave(paste(filePath, "plots/priors2-existence-", prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.pdf", sep=""), height = 14, width = 7)

```


### Posterior predictive


```{r q1.predictive}
m.predictive<-m.samples %>% filter(Parameter=='predictive')

ggplot(m.predictive,aes(x=Value, fill=Gender))+
  geom_histogram(position=position_dodge(), binwidth=0.03)+
  facet_wrap(~Item, scales='fixed')+
  xlab("% of Americans who ___")

ggsave(paste(filePath, "plots/priors2-existence-predictive-", prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.pdf", sep=""))


# fig.path <- "~/Documents/research/habituals/talks/lab-mtg-120115/images/"
# ggsave(paste(fig.path, "existentialQ-bda-histogram-priors1.pdf", sep=""), width = 8, height =5)
```


### Model - data fit


```{r q1.mdfit}



# create histogram from responses
d.freq<- d.tidy %>%
  select(item, menFreq, womenFreq) %>%
  gather(Gender, Human, menFreq, womenFreq) %>%
  mutate(Gender = factor(Gender, levels=c("menFreq", "womenFreq"),
                         labels=c("male", "female"))) %>%
  rename(Item = item) %>%
  mutate(Bin = round(Human, digits = 1)) %>%
  mutate(Bin = factor(Bin)) %>%
  group_by(Item, Gender, Bin) %>%
  summarize(count = length(Human)) %>%
  ungroup() %>%
  group_by(Item, Gender) %>%
  mutate(norm_count = count / sum(count)) %>%
  select(-count)


m.freq <- m.predictive %>% 
  mutate(Bin = round(Value, 1)) %>%
  mutate(Bin = factor(Bin)) %>%
  group_by(Item, Gender, Bin) %>%
  summarize(count = length(Value)) %>%
  ungroup() %>%
  group_by(Item, Gender) %>%
  mutate(model_count = count / sum(count)) %>%
  select(-count)

md.freq<- left_join(m.freq, d.freq)
md.freq[is.na(md.freq$norm_count),]$norm_count <- 0

ggplot(md.freq, aes(x=model_count, y=norm_count, color = Bin))+
  geom_point()+
  geom_abline(intercept = 0, slope = 1, lty = 2)+
  coord_fixed()

with(md.freq, cor(model_count, norm_count))^2
```



# Frequency question

```{r q2.load}
#prefix <- "waitQ-logNormalModel-incrMH"
prefix <- "waitQ-logNTimes-2logNormalsModel-1gender-incrMH"
#prefix <- "waitQ-poissonModel-incrMH"
samples <- 100000
burn <- samples / 2
m2<- as.data.frame.matrix(fread(paste(filePath, prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.csv",sep="")))

m2.samples <- m2[rep(row.names(m2), m2$Probability*(samples-burn)), 1:5]
m2.params<-m2.samples %>% filter(Parameter!='predictive')
m2.predictive<-m2.samples %>% filter(Parameter=='predictive')

```

### Posterior over parameters

```{r q2.params}

ggplot(m2.params,aes(x=Value, fill=Gender))+
  geom_histogram()+
  facet_grid(Item~Parameter, scales='free')+
  theme(strip.text.y = element_text(angle=0))


ggsave(paste(filePath, "plots/priors2-frequency-parameters-", prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.pdf", sep=""), height = 14, width = 7)


m2.params.stats <- m2.params %>%
  group_by(Parameter, Item, Gender) %>%
  summarize(MAP = estimate_mode(Value),
            credHigh = HPDhi(Value),
            credLow = HPDlo(Value))

ggplot(m2.params.stats,
       aes(x=Item, y=MAP, fill=Gender))+
  geom_bar(stat='identity', position=position_dodge())+
  geom_errorbar(aes(ymin = credLow, ymax = credHigh),
                position=position_dodge())+
  facet_wrap(~Parameter)+
  coord_flip()

ggsave(paste(filePath, "plots/priors2-frequency-stats-", prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.pdf", sep=""), height = 8, width = 10)
```


### Posterior predictive


```{r q2.predictive}

ggplot(m2.predictive,aes(x=Value, fill=Gender))+
  geom_histogram(position=position_dodge())+
  facet_wrap(~Item, scales='fixed')+
  xlim(-5,15)

ggsave(paste(filePath, "plots/priors2-frequency-log-predictive-", prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.pdf", sep=""), width =14, height = 6)


ggplot(m2.predictive,aes(x=exp(Value), fill=Gender))+
  geom_histogram(position=position_dodge())+
  facet_wrap(~Item, scales='fixed')+
  xlim(0,1500)


ggsave(paste(filePath, "plots/frequency-predictive-", prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.pdf", sep=""), width =14, height = 6)

```

# Model--data fit

```{r q2.mdfit}
# create histogram from responses
# d.rate<- d.tidy %>%
#   select(item, menRate, womenRate) %>%
#   gather(Gender, Human, menRate, womenRate) %>%
#   mutate(Gender = factor(Gender, levels=c("menRate", "womenRate"),
#                          labels=c("male", "female"))) %>%
#   rename(Item = item) %>%
#   mutate(Bin = round(log(Human), digits = 0)) %>%
#   mutate(Bin = factor(Bin)) %>%
# #  group_by(Item, Gender, Bin) %>%
#   group_by(Item, Bin) %>%
#   summarize(count = length(Human)) %>%
#   ungroup() %>%
#   group_by(Item) %>%
# #  group_by(Item, Gender) %>%
#   mutate(norm_count = count / sum(count)) %>%
#   select(-count)

nBins=10
d.times.bins<-d.nTimes %>%
  group_by(item) %>%
  summarize(lo_bar = round(quantile(logval, c(0)),1),
            hi_bar = round(quantile(logval, c(1)),1)) %>%
  mutate(bin_width = (hi_bar-lo_bar)/nBins)
                              

binSize=0.5

d.nTimes.binned<-left_join(d.nTimes,
                           d.times.bins) %>% 
  mutate(Bin = round(round(logval*1/bin_width, digits = 0)/(1/bin_width), digits=1)) %>%
  mutate(Bin = ifelse(Bin < lo_bar, lo_bar, Bin)) %>%
  mutate(Bin = ifelse(Bin > hi_bar, hi_bar, Bin)) %>%
  mutate(Bin = factor(Bin)) %>%
  rename(Item = item) %>%
  group_by(Item, Bin) %>%
  summarize(count = length(Bin)) %>%
  ungroup() %>%
  group_by(Item) %>%
#  group_by(Item, Gender) %>%
  mutate(norm_count = count / sum(count)) %>%
  select(-count)

m.rate <- left_join(m2.predictive,
                    d.times.bins %>%rename(Item =item)) %>% 
  mutate(Bin = round(round(Value*(1/bin_width), digits=0)/(1/bin_width), digits=1)) %>%
  mutate(Bin = ifelse(Bin < lo_bar, lo_bar, Bin)) %>%
  mutate(Bin = ifelse(Bin > hi_bar, hi_bar, Bin)) %>%
  mutate(Bin = factor(Bin)) %>%
  group_by(Item, Gender, Bin) %>%
  summarize(count = length(Value)) %>%
  ungroup() %>%
  group_by(Item, Gender) %>%
  mutate(model_count = count / sum(count)) %>%
  select(-count)

md.rate<- left_join(m.rate,
                    d.nTimes.binned) %>%
  mutate(Bin = to.n(Bin))
md.rate[is.na(md.rate$norm_count),]$norm_count <- 0

ggplot(md.rate, aes(x=model_count, y=norm_count, color = Bin))+
  geom_point()+
  geom_abline(intercept = 0, slope = 1, lty = 2)+
  coord_fixed()+
  xlim(-0.05,1.05)+
  ylim(-0.05,1.05)

with(md.rate, cor(model_count, norm_count))^2


md.rate<- md.rate %>%
  mutate(sqErr = (model_count - norm_count)^2)

View(md.rate)

ggsave(paste(filePath, "plots/priors2-reconstruction-10binsPerItem-", prefix, 
                   samples/1000, "k_burn", 
                   burn/1000, "k.pdf", sep=""))
```

```{r q2.deviations}
top5.dev<-md.rate[order(md.rate$sqErr, decreasing=T),]$Item[1:10]

md.dev<- md.rate %>% #filter(Item %in% top5.dev) %>%
  gather(src,val, model_count, norm_count)

ggplot(md.dev, aes(x = factor(Bin), y = val, fill=src))+
  geom_bar(stat='identity', position=position_dodge())+
  facet_wrap(~Item, scales='free')

```
# Scatterplot

```{r}
categs<-unique(read.csv("~/Documents/research/habituals/data/priors/priors-2.csv") %>%
  select(item, category) %>%
  rename(Item = item,
         Category = category))

```

```{r}

e.stats <- m.params %>%
  filter(Parameter == 'gamma') %>%
  group_by(Item, Gender) %>%
  summarize(eMAP = estimate_mode(Value),
            ecredHigh = HPDhi(Value),
            ecredLow = HPDlo(Value))
  

f.stats <- m2.params %>%
  filter(Parameter == 'mu') %>%
  group_by(Item, Gender) %>%
  summarize(fMAP = estimate_mode(Value),
            fcredHigh = HPDhi(Value),
            fcredLow = HPDlo(Value)) 


prior.stats<- left_join(left_join(e.stats, f.stats),
                        categs)


with(prior.stats, cor(fMAP, eMAP))^2


  ggplot(prior.stats, aes(x = eMAP, y = fMAP, color = Category, shape = Gender))+
  geom_point()+
  geom_errorbar(aes(ymin = fcredLow, ymax = fcredHigh))+
  geom_errorbarh(aes(xmin = ecredLow, xmax = ecredHigh))+
  xlab("% of Americans who have DONE ACTION")+
  ylab("Log Interval Time of DOING ACTION")+
  theme_paper()+
  #scale_color_solarized()
  scale_color_brewer(palette='Set1')

ggsave("~/Documents/research/habituals/writing/_cogsci2016/figures/prior-scatter.pdf")

```



## Posterior predictive (the cheap way)

Reconstruct prevalence prior by forward sampling

```{r posterior.predictive.forwardSample}


shape1 = function(gamma,delta){return (gamma * delta)}
shape2= function(gamma,delta){return ((1-gamma) * delta)}

d.samples<-data.frame()

for (i in 1:100){

  d.samp.exis<-m.params %>%
    group_by(Item, Gender, Parameter) %>%
    sample_n(1) %>%
    ungroup() %>%
    spread(Parameter, Value) %>%
    mutate(alpha = shape1(gamma,delta),
           beta = shape2(gamma, delta)) %>%
    group_by(Item, Gender) %>%
    mutate(prob_hasF = rbeta(1, alpha, beta)) %>%
    mutate(hasDoneA = rbinom(1,1,prob_hasF)) %>%
    select(-gamma, -delta, -Measure)

  
    d.freq.samp<-m2.params %>%
    group_by(Item, Gender, Parameter) %>%
    sample_n(1) %>%
    ungroup() %>%
      spread(Parameter, Value) %>%
      select(-Measure)
    
    d.samp <- left_join(d.samp.exis, d.freq.samp)
  
  for (k in 1:length(d.samp$Item)){
    d.iter<-data.frame(
               Item = d.samp[k,1],
               Gender = d.samp[k,2],
               Frequency = if (d.samp[[k,"hasDoneA"]]==1){
                                rnorm(50, d.samp[[k, "mu"]], 
                                          d.samp[[k, "sigma"]]
                                    )
                                } else {rep(10,50)}
               )
    d.samples<-bind_rows(d.samples, d.iter)
  }
  
  if ((i %% 10)==0) { print(i) }
}

```



```{r}


# d.samples<-d.samples %>%
#   rowwise() %>%
#   mutate(Frequency = ifelse(Prevalence==0, 10, Prevalence))


for (t in levels(factor(d.samples$Item))){
  
 ggplot(d.samples %>% filter(Item == t), 
         aes(x=Frequency, color = Gender))+
    geom_density(aes(y=..scaled..), 
                 size=1, 
                 alpha = 0.3,
                 #color ='black',
                 fill='black')+
    theme_paper()+
    scale_color_solarized()+
    #scale_color_manual(values=c("#bdbdbd","#f0f0f0"))+
    scale_alpha_manual(values=c(0.6,0.1))+
    #geom_density(size=1, alpha=0.7)+
#      geom_errorbarh(data = m.prevTargets %>% filter(Property==t),
#                     aes(x= map, xmin = credLow, xmax = credHigh,
#                     y = 1.05), color='#2ca25f', size = 1.1,
#                     height = 0.1, inherit.aes=F)+
    scale_linetype_manual(values=c(1,2))+
    xlab("Log Interval time")+
    guides(fill=F, alpha=F, linetype=F)+
    facet_wrap(~Item, scales='free')+
    scale_x_continuous(limits=c(-1,10), breaks=c(0,2,4,6,8,10))+
    scale_y_continuous(limits=c(0,1.1), breaks=c(0,0.5,1))+
    ylab("Scaled density")+
    theme(strip.text.x=element_text(size=16))+
    coord_fixed()
      

ggsave(file=paste('~/Documents/research/habituals/writing/_cogsci2016/figures/interval-priors-',t,'.pdf',sep=''), width=5, height=3.5)

print(t)

}

```

